# This is a basic workflow to help you get started with Actions

name: Resolvers

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #schedule:
  #  - cron: '0 5 * * *'
  # Remove both comments to run this action on daily basis.
  workflow_dispatch:
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      # Runs a single command using the runners shell
      - name: Setting up Go Tool
        env:
          GO111MODULE: on
        run: |
          go install -v github.com/tomnomnom/anew@latest
        shell: bash
      
      - name: Cache Go
        id: cache-go
        uses: actions/cache@v2
        with:
          path: /home/runner/go
          key: ${{ runner.os }}-go

      - name: Setting up and Running DnsValidator
        run: |
          curl --silent https://raw.githubusercontent.com/BBerastegui/fresh-dns-servers/master/resolvers.txt | egrep '^1[.]0[.]|^1[.]1' > dailydns.txt
          #curl --silent https://raw.githubusercontent.com/blechschmidt/massdns/master/lists/resolvers.txt | egrep '^1[.]0[.]|^1[.]1'| anew -q dailydns.txt
          #curl --silent https://raw.githubusercontent.com/janmasarik/resolvers/master/resolvers.txt |egrep '^1[.]0[.]|^1[.]1' | anew -q dailydns.txt
          #curl --silent https://public-dns.info/nameservers.txt |egrep '^1[.]0[.]|^1[.]1' | anew -q dailydns.txt
          #curl --silent https://raw.githubusercontent.com/bp0lr/dmut-resolvers/main/resolvers.txt | egrep '^1[.]0[.]|^1[.]1' | anew -q dailydns.txt
          #curl --silent https://raw.githubusercontent.com/Phasip/resolvers/master/resolvers.txt | egrep '^1[.]0[.]|^1[.]1' | anew -q dailydns.txt
          #curl --silent https://raw.githubusercontent.com/proabiral/Fresh-Resolvers/master/resolvers.txt | egrep '^1[.]0[.]|^1[.]1' | anew -q dailydns.txt
          #curl --silent https://raw.githubusercontent.com/indianajson/trusty-resolvers/master/top-resolvers | egrep '^1[.]0[.]|^1[.]1' | anew -q dailydns.txt
          #curl --silent https://raw.githubusercontent.com/trickest/resolvers/main/resolvers.txt | egrep '^1[.]0[.]|^1[.]1' | anew -q dailydns.txt
          cat dailydns.txt | grep -E "(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])" > dailydnsx.txt
          output/./dnsvalidator -tL dailydnsx.txt --silent -timeout 100 -threads 50 > ../output/freshresolvers.txt
          curl --silent https://raw.githubusercontent.com/BonJarber/fresh-resolvers/main/resolvers.txt | egrep '^1[.]0[.]|^1[.]1' | anew -q ../output/freshresolvers.txt
        shell: bash

      - name: Create local changes
        run: |
          git add ../output/freshresolvers.txt
      
      - name: Commit results to Github
        run: |
          git config --local user.email "actions@github.com"
          git config --global user.name "githubactions"
          git commit -m "Resolvers" -a --allow-empty

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
