# This is a basic workflow to help you get started with Actions

name: Resolvers

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    - cron: "05 02 * * *"
  # Remove both comments to run this action on daily basis.
  #workflow_dispatch:
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      # Runs a single command using the runners shell
      - name: Setting up Go Tool
        env:
          GO111MODULE: on
        run: |
          go get -v github.com/tomnomnom/anew
        shell: bash
      
      - name: Cache Go
        id: cache-go
        uses: actions/cache@v2
        with:
          path: /home/runner/go
          key: ${{ runner.os }}-go

      - name: Setting up and Running DnsValidator
        run: |
          git clone https://github.com/vortexau/dnsvalidator
          cd dnsvalidator
          pip3 install wheel
          pip3 install setuptools
          sudo python3 setup.py install
          cd ..
          curl --silent https://raw.githubusercontent.com/BBerastegui/fresh-dns-servers/master/resolvers.txt | egrep -v '^1[.]0[.]|^1[.]1' > dailydns.txt
          curl --silent https://raw.githubusercontent.com/janmasarik/resolvers/master/resolvers.txt | egrep -v '^1[.]0[.]|^1[.]1' | anew -q dailydns.txt
          curl --silent https://public-dns.info/nameservers.txt |egrep -v '^1[.]0[.]|^1[.]1'| egrep -v '^1[.]0[.]|^1[.]1' | anew -q dailydns.txt
          curl --silent https://raw.githubusercontent.com/bp0lr/dmut-resolvers/main/resolvers.txt | egrep -v '^1[.]0[.]|^1[.]1' | anew -q dailydns.txt
          dnsvalidator -tL dailydns.txt --silent -threads 10 > output/freshresolvers.txt
        shell: bash

      - name: Create local changes
        run: |
          git add output/freshresolvers.txt
      
      - name: Commit results to Github
        run: |
          git config --local user.email "actions@github.com"
          git config --global user.name "githubactions"
          git commit -m "Resolvers" -a --allow-empty

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
