name: FreshDnsResolvers

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
  - cron: '0 5 * * *'
  # Remove both comments to run this action on daily basis.
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7.1' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

      - name: Setup golang
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - run: go version

      - name: Settingup Tools
        env:
          GO111MODULE: on
        run: |
          go install -v github.com/tomnomnom/anew@latest
        shell: bash
      
      - name: Cache Go
        id: cache-go
        uses: actions/cache@v2
        with:
          path: /home/runner/go
          key: ${{ runner.os }}-go

      - name: Running DnsValidator
        run: |
          git clone https://github.com/vortexau/dnsvalidator
          cd dnsvalidator
          pip3 install wheel
          pip3 install setuptools
          sudo python3 setup.py install
          rm ../output/freshresolvers.txt
          curl --silent https://raw.githubusercontent.com/BBerastegui/fresh-dns-servers/master/resolvers.txt | egrep '^1[.]0[.]|^1[.]1' > dailydns.txt
          curl --silent https://raw.githubusercontent.com/janmasarik/resolvers/master/resolvers.txt |egrep '^1[.]0[.]|^1[.]1' | anew -q dailydns.txt
          curl --silent https://raw.githubusercontent.com/blechschmidt/massdns/master/lists/resolvers.txt | egrep '^1[.]0[.]|^1[.]1' | anew -q dailydns.txt
          curl --silent https://raw.githubusercontent.com/Phasip/resolvers/master/resolvers.txt | egrep '^1[.]0[.]|^1[.]1' | anew -q dailydns.txt
          curl --silent https://raw.githubusercontent.com/proabiral/Fresh-Resolvers/master/resolvers.txt | egrep '^1[.]0[.]|^1[.]1' | anew -q dailydns.txt
          curl --silent https://raw.githubusercontent.com/trickest/resolvers/main/resolvers.txt | egrep '^1[.]0[.]|^1[.]1' | anew -q dailydns.txt
          cat dailydns.txt | grep -E "(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])" > dailydnsx.txt
          dnsvalidator --silent -tL dailydnsx.txt -threads 50 -timeout 100 -threads 50 -o ../output/freshresolvers.txt
          curl --silent https://raw.githubusercontent.com/BonJarber/fresh-resolvers/main/resolvers.txt | egrep '^1[.]0[.]|^1[.]1' | anew -q ../output/freshresolvers.txt
        shell: bash

      - name: Create local changes
        run: |
          git add ../output/freshresolvers.txt
      
      - name: Commit results to Github
        run: |
          git config --local user.email "actions@github.com"
          git config --global user.name "githubactions"
          git commit -m "PD-Actions report" -a --allow-empty

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
